### ISSUE TITLE
User confusion on setup steps

### ISSUE THREAD

**Issue by mxmilkiib** [impredicative/irc-rss-feed-bot#68]
I'm trying to get setup for the first time, dusting off my docker skills, not sure if I might have missed a step?

```
$ docker images                                                                                                                                                                                       
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE                                                                                                                     
<none>                       <none>              fe5a53c5e6c8        11 hours ago        507MB                                                                                                                    
ascensive/irc-rss-feed-bot   latest              04ec735e21e1        11 days ago         395MB                                                                                                                    
python                       3.8-slim-buster     41dcfe21e8fd        2 weeks ago         113MB                                                                                                                    

$ docker run -v $(pwd)/docker/config.yaml:/config/config.yaml 04ec735e21e1                                                                                                                            
2020-11-04 04:20:47,983 INFO MainThread-7f3639f8f740:ircrssfeedbot.main:29:load_instance_config: Read user configuration file /config/config.yaml                                                                 
2020-11-04 04:20:47,983 INFO MainThread-7f3639f8f740:ircrssfeedbot.main:48:load_instance_config: The excerpted configuration for 1 channels with 1 feeds having 1 unique URLs is:                                 
{'host': 'chat.freenode.net', 'ssl_port': 6697, 'nick': 'lavb0t', 'admin': 'milkii!milkii@thingsandstuff.org', 'alerts_channel': '#libreavargh', 'mode': '+igR', 'defaults': {'new': 'all'}}
2020-11-04 04:20:47,983 INFO MainThread-7f3639f8f740:ircrssfeedbot.main:59:load_instance_config: #libreav has 1 feeds: libreav
2020-11-04 04:20:47,983 INFO MainThread-7f3639f8f740:ircrssfeedbot.main:68:load_instance_config: #libreav has no foreground colors in use.
2020-11-04 04:20:47,991 INFO MainThread-7f3639f8f740:ircrssfeedbot.bot:41:__init__: Initializing bot as: uid=999(app) gid=999(app) groups=999(app)                                                                
Traceback (most recent call last):                                                                                                                                                                                
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 3035, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 3370, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 3097, in execute_sql
    cursor = self.cursor(commit)
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 3081, in cursor
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 3038, in connect
    self._initialize_connection(self._state.conn)
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 2873, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 3035, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 3370, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/ircrssfeedbot/__main__.py", line 8, in <module>
    main()
  File "/app/ircrssfeedbot/main.py", line 95, in main
    Bot()
  File "/app/ircrssfeedbot/bot.py", line 45, in __init__
    self._db = Database()
  File "/app/ircrssfeedbot/db.py", line 43, in __init__
    self._db.create_tables([Post])
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 3286, in create_tables
    model.create_table(**options)
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 6595, in create_table
    cls._schema.create_all(safe, **options)
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 5731, in create_all
    self.create_table(safe, **table_options)
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 5586, in create_table
    self.database.execute(self._create_table(safe=safe, **options))
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 3112, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 3106, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 2873, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 3097, in execute_sql
    cursor = self.cursor(commit)
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 3081, in cursor
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 3038, in connect
    self._initialize_connection(self._state.conn)
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 2873, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 3035, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 3370, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file
```

**Comment by impredicative** [comment]
I have no idea what is happening here. Why not use a `docker-compose.yml` file or better container manager? An example of it is in the readme.

Let me then see your `config.yaml` file.

Ensure the directory used by the container is writable.

**Comment by impredicative** [comment]
The readme already mentions to make the directory writable by using a command such as `chmod -R a+w ./irc-rss-feed-bot`.

**Comment by mxmilkiib** [comment]
Thanks for the assist. Crossed wires due to my inexperience with Docker and finding the README somewhat ambiguous ("Deployment" after "Usage", use of "recommended" and "possibly" in the sentence relating to Docker Compose) (and that box, at that point, being 18.04 LTS so failing when trying to run before upgrade). Sorted and running after realising stock Vim gg=G doesn't help for yaml indentation. Cheers again.

**Comment by impredicative** [comment]
PyCharm is good for editing YAML. If you have specific recommendations for improvements to the readme, please make a list. I can move Deployment to be above Usage.

**Comment by mxmilkiib** [comment]
Cool, Deployment first I think would help nudge the path of a new or forgetful user in the right direction.

Possibly also providing template config/compose/secret files might be worth it?

Another thought I had before was suggesting a vim [modeline](https://stackoverflow.com/a/55019129) start.

I've got vim yaml syntax fine locally, so I was going to sshfs in in future :)

**Comment by impredicative** [comment]
I strongly advise version controlling all config files used for this bot. I personally also use git to push and pull them into the machine where the bot runs.

**Comment by impredicative** [comment]
Upon further examination, unfortunately the Deployment section in the readme cannot presently be moved above the Usage section. That's because the Deployment section makes numerous references to points covered in the Usage section. In contrast, the Usage section doesn't make references to points covered in the Deployment section.

A forkable configuration repo may still be a good idea. I will consider it independently.

To be clear, you don't strictly need Docker Compose. Just plain docker also works, but Docker Compose makes it easier for me to offer any feedback for your setup.
