### ISSUE TITLE
AttributeError: 'types.SimpleNamespace' object has no attribute 'identity'

### ISSUE THREAD

**Issue by mxmilkiib** [impredicative/irc-rss-feed-bot#70]
I got the bot joining the channels but nothing was coming through. The log has a lot of these;

```
2020-11-09 22:45:07,971 INFO FeedReader-#libreav-libreav-7f9202d97700:ircrssfeedbot.bot:272:_read_feed: Retrieved in 0.6s the feed libreav of #libreav with 10 approved entries via 1 URLs read bypassing cache.
2020-11-09 22:45:07,975 INFO ChannelMessenger-#libreav-7f9203598700:ircrssfeedbot.db:85:select_unposted_for_channel: Returning 10 unposted URLs from the database for channel #libreav having ignored feed libreav out of 10 URLs.
2020-11-09 22:45:07,976 INFO ChannelMessenger-#libreav-7f9203598700:ircrssfeedbot.feed:413:post: Posting 10 entries for feed libreav of #libreav.
2020-11-09 22:45:09,979 ERROR ChannelMessenger-#libreav-7f9203598700:ircrssfeedbot.bot:324:alerter: Error processing feed libreav of #libreav: 'types.SimpleNamespace' object has no attribute 'identity'
Traceback (most recent call last):
  File "/app/ircrssfeedbot/bot.py", line 220, in _msg_channel
    feed.post()
  File "/app/ircrssfeedbot/feed.py", line 419, in post
    msg = entry.message
  File "/app/ircrssfeedbot/entry.py", line 104, in message
    format_map = dict(identity=config.runtime.identity, channel=self.feed_reader.channel, feed=_style_name(self.feed_reader.name), url=self.short_url or self.long_url)
AttributeError: 'types.SimpleNamespace' object has no attribute 'identity'
```

FWIW, [the feed](https://libreav.org/updates/feed).

**Comment by impredicative** [comment]
Show the config yaml.

**Comment by impredicative** [comment]
Make sure the nick is registered and identified with nickserv. Make sure the email behind the nick is verified.

**Comment by mxmilkiib** [comment]
Thank you, working now :)
