### ISSUE TITLE
Cache directory "/app/.ircrssfeedbot_cache/URLReader"

### ISSUE THREAD

**Issue by ssbarnea** [impredicative/irc-rss-feed-bot#78]
Apparently something changed since last time I used the feed bot and it no longer starts inside containers. It is bit weird because I did not see /app as being configured anywhere.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/ircrssfeedbot/__main__.py", line 6, in <module>
    from ircrssfeedbot.main import main
  File "/app/ircrssfeedbot/main.py", line 11, in <module>
    from ircrssfeedbot.bot import Bot
  File "/app/ircrssfeedbot/bot.py", line 17, in <module>
    from . import config, publishers, searchers
  File "/app/ircrssfeedbot/publishers/__init__.py", line 2, in <module>
    from . import github
  File "/app/ircrssfeedbot/publishers/github.py", line 12, in <module>
    from ._base import BasePublisher
  File "/app/ircrssfeedbot/publishers/_base.py", line 12, in <module>
    from ..feed import FeedEntry
  File "/app/ircrssfeedbot/feed.py", line 21, in <module>
    from .url import URLReader
  File "/app/ircrssfeedbot/url.py", line 106, in <module>
    class URLReader:
  File "/app/ircrssfeedbot/url.py", line 109, in URLReader
    _CACHE = diskcache.Cache(directory=config.DISKCACHE_PATH / "URLReader", timeout=2, size_limit=config.DISKCACHE_SIZE_LIMIT)
  File "/usr/local/lib/python3.8/site-packages/diskcache/core.py", line 481, in __init__
    raise EnvironmentError(
PermissionError: [Errno 13] Cache directory "/app/.ircrssfeedbot_cache/URLReader" does not exist and could not be created
```

**Comment by impredicative** [comment]
The Dockerfile does a few things:

```Dockerfile
WORKDIR /app
RUN set -x && \
    groupadd -g 999 app && \
    useradd -r -m -u 999 -g app app && \
    mkdir -v ./.ircrssfeedbot_cache && \
    chown -v app:app ./.ircrssfeedbot_cache
USER app
```

It is not however creating "/app/.ircrssfeedbot_cache/URLReader" or any of its required subdirectories.
If you're running the image as a different user, it may not have the required permissions on the directory.

As a troubleshooting step, perhaps you can try including `USER app` or `RUN chmod a+rw /app/.ircrssfeedbot_cache` in your Dockerfile if you have one. If you use `chmod` but not `USER`, you may still encounter other permissions issues. Let's see if you do.

Alternatively, do you have any recommendation for changes to my Dockerfile?

**Comment by impredicative** [comment]
@ssbarnea Or should I forget about the `app` user and run the bot as the default root user? I'm not exactly sure. I have previously read that it's advisable to use a non-root user in the image.

**Comment by impredicative** [comment]
I'm not sure if I understand this issue. Are you saying you're running docker in docker?

For what it's worth, there shouldn't be any meaningful difference between the image on Docker Hub and the one that's built locally. Both work for me.
